
variables:
  PROJECT_NAME: "$CI_PROJECT_NAME"
  
types:
  - build
  - deploy

build_app:
  only:
   - master
   - trigger
  type: build
  script: 
   - make build
   - make test
   - make clean

deploy_app:
  only:
   - master
   - trigger
  type: deploy
  script:
   - make build
   - docker push bigr.bios.cf.ac.uk:4567/$CI_PROJECT_PATH
